### ISSUE TITLE
Offer a way to allow individual players to stop receiving the automatic sorting message after closing a chest

### ISSUE THREAD

**Issue by rutzfutz** [JEFF-Media-GbR/Spigot-ChestSort#106]
**Is your feature request related to a problem? Please describe.**
I'm currently running ChestSort with the following configuration regarding automatic sorting (I skipped all non-related lines):
```yml
allow-automatic-sorting: true
sorting-enabled-by-default: false
show-message-when-using-chest: true
show-message-when-using-chest-and-sorting-is-enabled: false
show-message-again-after-logout: true
```

This causes ChestSort to announce the automatic sorting functionality once per player session, allowing players who miss the message at first to see it again after a logout and relogin. This is great so far.

However, I have certain players on my server (including myself) who do NOT want the automatic sorting to be enabled, but prefer the hotkey-based sorting instead, and are therefore annoyed by the repeated reminders about the automatic sorting.

**Describe the solution you'd like**
I would like to offer a simple way to players to turn off the automatic sorting message for themselves.

It could be as easy as remembering that the player used the `/chestsort (off/toggle)` command to turn sorting off. It's safe to assume that players who used this command are aware of ChestSort and therefore do not need repeated messages about the automatic sorting feature.

If you're unsure whether some admins would miss the repeated messages in this scenario and prefer the old behavior, you could add a `show-message-when-using-chest-and-sorting-was-disabled-by-player` setting (default: `false`) and thereby allow them to re-enable it.

**Describe alternatives you've considered**
I could change the config setting `show-message-again-after-logout` to `false`, but this would prevent players who missed the message at first to discover the functionality later.

**Additional context**
My ChestSort version is 9.3.0 running on PaperMC build 484 (MC: 1.16.5).
