### ISSUE TITLE
Sorts occurs with every hot key, no matter the configuration

### ISSUE THREAD

**Issue by almino** [JEFF-Media-GbR/Spigot-ChestSort#110]
**Used ChestSort version**
```[16:09:39 INFO]: [ChestSort] Enabling ChestSort v9.7.1```

**Used Spigot version**
```paper-1.16.5-595.jar```

**Describe the bug**
All sorting hotkeys works even though it is disabled.

**To Reproduce**
plugins/ChestSort/config.yml:
```yaml
# You can define which sorting hotkeys are enabled by default.
# Players can also enable/disable these shortcuts individually via /chestsort hotkeys
# Hotkeys that could interfere with Minecraft's normal behaviour (e.g.
# shift+left-click) only work on empty slots, so don't worry about them.
sorting-hotkeys:
  # Use middle click (mousewheel) on ANY inventory slot as hotkey
  middle-click: true
  # Use shift + left-click on any EMPTY inventory slot as hotkey
  shift-click: false
  # Use double left-click on any EMPTY inventory slot as hotkey
  double-click: false
  # Use shift + right-click on any EMPTY inventory slot as hotkey
  shift-right-click: false
```
Shift + right click any empty slot on your inventory and it sorts.
Double click anywhere in hot bar and the hotbar is sorted.

**Expected behavior**
Using the configuration above, only middle click should do the sorting.

**Additional context**
None.
